spring:
  application:
    name: API-GATEWAY
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
       routes:
#        - id: PRODUCT-SERVICE
#          uri: lb://PRODUCT-SERVICE
#          predicates:
#            - Path=/product/**
#          filters:
#            - PrefixPath=/api

        - id: MANIFEST-SERVICE
          uri: lb://MANIFEST-SERVICE
          predicates:
            - Path=/mani/**
          filters:
            - PrefixPath=/api

        - id: BANK-SERVICE
          uri: lb://BANK-SERVICE
          predicates:
              - Path=/bank-card/**
          filters:
              - PrefixPath=/api

        - id: TRANS-SERVICE
          uri: lb://TRANS-SERVICE
          predicates:
            - Path=/trans/**
          filters:
#            - AddResponseHeader=my-response-header,product.ejavaexample.org
            - PrefixPath=/api

#        - id: USER-SERVICE
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user/**
#          filters:
##            - AddResponseHeader=my-response-header,user.ejavaexample.org
#            - PrefixPath=/api
##            - MyPreFilter

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
#            - AddResponseHeader=my-response-header,auth.ejavaexample.org
            - PrefixPath=/api 

            


server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
      
